import { lazy } from 'react'

import type { TRoute } from '@shared/types/modal'

const AboutExtraIdToReceiveModal = lazy(() => import('./modals/AboutExtraIdToReceive'))
const AddAddressModal = lazy(() => import('./modals/AddAddress'))
const AddCustomNetworkModal = lazy(() => import('./modals/AddCustomNetwork'))
const AddNetworkProfileModal = lazy(() => import('./modals/AddNetworkProfile'))
const BlockchainSelectionModal = lazy(() => import('./modals/BlockchainSelection'))
const BuyAndSellTokensAboutDataModal = lazy(() => import('./modals/BuyAndSellTokensAboutData'))
const ConfirmActionModal = lazy(() => import('./modals/ConfirmAction'))
const ConfirmPasswordBackupModal = lazy(() => import('./modals/ConfirmPasswordBackup'))
const ConfirmPasswordExportModal = lazy(() => import('./modals/ConfirmPasswordExport'))
const ConfirmPasswordRecoverModal = lazy(() => import('./modals/ConfirmPasswordRecover'))
const CreateWalletStep1Modal = lazy(() => import('./modals/CreateWalletStep1'))
const CreateWalletStep2Modal = lazy(() => import('./modals/CreateWalletStep2'))
const CreateWalletStep3Modal = lazy(() => import('./modals/CreateWalletStep3'))
const CreateWalletStep4Modal = lazy(() => import('./modals/CreateWalletStep4'))
const CreateWalletStep5Modal = lazy(() => import('./modals/CreateWalletStep5'))
const DappDisconnectionModal = lazy(() => import('./modals/DappDisconnection'))
const DecryptKeyModal = lazy(() => import('./modals/DecryptKey'))
const DeleteAccountModal = lazy(() => import('./modals/DeleteAccount'))
const DeleteContactModal = lazy(() => import('./modals/DeleteContact'))
const DeleteWalletModal = lazy(() => import('./modals/DeleteWallet'))
const EditWalletModal = lazy(() => import('./modals/EditWallet'))
const ErrorModal = lazy(() => import('./modals/Error'))
const ExportKeyModal = lazy(() => import('./modals/ExportKey'))
const ExportMnemonicModal = lazy(() => import('./modals/ExportMnemonic'))
const ImportAccountsSelectionModal = lazy(() => import('./modals/ImportAccountsSelection'))
const ImportModal = lazy(() => import('./modals/Import'))
const ImportWatchAccountsModal = lazy(() => import('./modals/ImportWatchAccounts'))
const NeonMigrateStep2Modal = lazy(() => import('./modals/NeonMigrateStep2'))
const NeonMigrateStep3Modal = lazy(() => import('./modals/NeonMigrateStep3'))
const NeonMigrateStep4Modal = lazy(() => import('./modals/NeonMigrateStep4'))
const Nep6BackupImportStep3Modal = lazy(() => import('./modals/Nep6BackupImportStep3'))
const Nep6BackupImportStep4Modal = lazy(() => import('./modals/Nep6BackupImportStep4'))
const Neo3NeoxBridgeConfirmationModal = lazy(() => import('./modals/Neo3NeoxBridgeConfirmation'))
const Neo3NeoxBridgeDetailsModal = lazy(() => import('./modals/Neo3NeoxBridgeDetails'))
const NetworkUrlSelectionModal = lazy(() => import('./modals/NetworkUrlSelection'))
const NetworkSelectionModal = lazy(() => import('./modals/NetworkSelection'))
const NFTSelectionModal = lazy(() => import('./modals/NftSelection'))
const NotificationsModal = lazy(() => import('./modals/Notifications'))
const PersistAccountModal = lazy(() => import('./modals/PersistAccount'))
const PersistContactModal = lazy(() => import('./modals/PersistContact'))
const SelectAccountModal = lazy(() => import('./modals/SelectAccount'))
const SelectContactModal = lazy(() => import('./modals/SelectContact'))
const SellTokensDepositModal = lazy(() => import('./modals/SellTokensDeposit/index'))
const SuccessModal = lazy(() => import('./modals/Success'))
const SupportTicketModal = lazy(() => import('./modals/SupportTicket'))
const SwapDetailsLogModal = lazy(() => import('./modals/SwapDetailsLog'))
const SwapDetailsModal = lazy(() => import('./modals/SwapDetails'))
const Neo3VoteCandidateDetailsModal = lazy(() => import('./modals/Neo3VoteCandidateDetails'))
const StellarTrustlinesModal = lazy(() => import('./modals/StellarTrustlines'))
const StellarPersistTrustlineModal = lazy(() => import('./modals/StellarPersistTrustline'))

const sideModalsRouter: TRoute[] = [
  { name: 'about-extra-id-to-receive', element: AboutExtraIdToReceiveModal },
  { name: 'add-address', element: AddAddressModal },
  { name: 'add-custom-network', element: AddCustomNetworkModal },
  { name: 'add-network-profile', element: AddNetworkProfileModal },
  { name: 'blockchain-selection', element: BlockchainSelectionModal },
  { name: 'buy-and-sell-tokens-about-data', element: BuyAndSellTokensAboutDataModal },
  { name: 'confirm-action', element: ConfirmActionModal },
  { name: 'confirm-password-backup', element: ConfirmPasswordBackupModal },
  { name: 'confirm-password-export', element: ConfirmPasswordExportModal },
  { name: 'confirm-password-recover', element: ConfirmPasswordRecoverModal },
  { name: 'create-wallet-step-1', element: CreateWalletStep1Modal },
  { name: 'create-wallet-step-2', element: CreateWalletStep2Modal },
  { name: 'create-wallet-step-3', element: CreateWalletStep3Modal },
  { name: 'create-wallet-step-4', element: CreateWalletStep4Modal },
  { name: 'create-wallet-step-5', element: CreateWalletStep5Modal },
  { name: 'dapp-disconnection', element: DappDisconnectionModal },
  { name: 'decrypt-key', element: DecryptKeyModal },
  { name: 'delete-account', element: DeleteAccountModal },
  { name: 'delete-contact', element: DeleteContactModal },
  { name: 'delete-wallet', element: DeleteWalletModal },
  { name: 'edit-wallet', element: EditWalletModal },
  { name: 'error', element: ErrorModal },
  { name: 'export-key', element: ExportKeyModal },
  { name: 'export-mnemonic', element: ExportMnemonicModal },
  { name: 'import', element: ImportModal },
  { name: 'import-accounts-selection', element: ImportAccountsSelectionModal },
  { name: 'import-watch-accounts', element: ImportWatchAccountsModal },
  { name: 'neon-migrate-step-2', element: NeonMigrateStep2Modal },
  { name: 'neon-migrate-step-3', element: NeonMigrateStep3Modal },
  { name: 'neon-migrate-step-4', element: NeonMigrateStep4Modal },
  { name: 'nep6-backup-import-step-3', element: Nep6BackupImportStep3Modal },
  { name: 'nep6-backup-import-step-4', element: Nep6BackupImportStep4Modal },
  { name: 'neo3-neox-bridge-confirmation', element: Neo3NeoxBridgeConfirmationModal },
  { name: 'neo3-neox-bridge-details', element: Neo3NeoxBridgeDetailsModal },
  { name: 'network-url-selection', element: NetworkUrlSelectionModal },
  { name: 'network-selection', element: NetworkSelectionModal },
  { name: 'nft-selection', element: NFTSelectionModal },
  { name: 'notifications', element: NotificationsModal },
  { name: 'persist-account', element: PersistAccountModal },
  { name: 'persist-contact', element: PersistContactModal },
  { name: 'select-account', element: SelectAccountModal },
  { name: 'select-contact', element: SelectContactModal },
  { name: 'sell-tokens-deposit', element: SellTokensDepositModal },
  { name: 'success', element: SuccessModal },
  { name: 'support-ticket', element: SupportTicketModal },
  { name: 'swap-details', element: SwapDetailsModal },
  { name: 'swap-details-log', element: SwapDetailsLogModal },
  { name: 'neo3-vote-candidate-details', element: Neo3VoteCandidateDetailsModal },
  { name: 'stellar-trustlines', element: StellarTrustlinesModal },
  { name: 'stellar-persist-trustlines', element: StellarPersistTrustlineModal },
]

const AutoUpdateCompletedModal = lazy(() => import('./modals/AutoUpdateCompleted'))
const AutoUpdateMobileModal = lazy(() => import('./modals/AutoUpdateMobile'))
const AutoUpdateNotesModal = lazy(() => import('./modals/AutoUpdateNotes'))
const AssistantNewConversationDiscardAlertModal = lazy(() => import('./modals/AssistantNewConversationDiscardAlert'))
const BuyAndSellTokensLeaveAlertModal = lazy(() => import('./modals/BuyAndSellTokensLeaveAlert'))
const ConnectHardwareWalletModal = lazy(() => import('./modals/ConnectHardwareWallet'))
const DappConnectionModal = lazy(() => import('./modals/DappConnection'))
const DappConnectionRequest = lazy(() => import('./modals/DappConnectionRequest'))
const DappPermissionModal = lazy(() => import('./modals/DappPermission'))
const DappPermissionContractDetailsModal = lazy(() => import('./modals/DappPermissionContractDetails'))
const DappPermissionSignatureScopeModal = lazy(() => import('./modals/DappPermissionSignatureScope'))
const ExportFullTransactionsModal = lazy(() => import('./modals/ExportFullTransactions'))
const HideFraudulentTokenModal = lazy(() => import('./modals/HideFraudulentToken'))
const SearchModal = lazy(() => import('./modals/Search'))
const Neo3VoteConfirmationModal = lazy(() => import('./modals/Neo3VoteConfirmation'))
const Neo3VoteSuccessModal = lazy(() => import('./modals/Neo3VoteSuccess'))
const Neo3VoteSupportUsModal = lazy(() => import('./modals/Neo3VoteSupportUs'))

const centerModalsRouter: TRoute[] = [
  { name: 'assistant-new-conversation-discard-alert', element: AssistantNewConversationDiscardAlertModal },
  { name: 'auto-update-completed', element: AutoUpdateCompletedModal },
  { name: 'auto-update-mobile', element: AutoUpdateMobileModal },
  { name: 'auto-update-notes', element: AutoUpdateNotesModal },
  { name: 'buy-and-sell-tokens-leave-alert', element: BuyAndSellTokensLeaveAlertModal },
  { name: 'connect-hardware-wallet', element: ConnectHardwareWalletModal },
  { name: 'dapp-connection', element: DappConnectionModal },
  { name: 'dapp-connection-request', element: DappConnectionRequest },
  { name: 'dapp-permission', element: DappPermissionModal },
  { name: 'dapp-permission-contract-details', element: DappPermissionContractDetailsModal },
  { name: 'dapp-permission-signature-scope', element: DappPermissionSignatureScopeModal },
  { name: 'export-full-transactions', element: ExportFullTransactionsModal },
  { name: 'hide-fraudulent-token', element: HideFraudulentTokenModal },
  { name: 'search', element: SearchModal },
  { name: 'neo3-vote-confirmation', element: Neo3VoteConfirmationModal },
  { name: 'neo3-vote-success', element: Neo3VoteSuccessModal },
  { name: 'neo3-vote-support-us', element: Neo3VoteSupportUsModal },
]

export const modalsRouter = [sideModalsRouter, centerModalsRouter]
