version: 2.1

orbs:
  win: circleci/windows@5.0.0
  python: circleci/python@2.0.3
  node: circleci/node@5.1.0

references:
  container_config: &container_config
    docker:
      - image: cimg/node:current
    working_directory: ~/neon-wallet-desktop

commands:
  prepare_linux:
    steps:
      - checkout
      - node/install:
          node-version: '20.17.0'
      - run: sudo npm install -g npm
      - restore_cache:
          key: nwd-dependency-cache-{{ checksum "package.json" }}
      - run: sudo apt-get -y update
      - run: sudo apt-get -y install libusb-1.0-0-dev libudev-dev python3 python3-pip
      - run: npm ci --timeout 1500000
      - save_cache:
          key: nwd-dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
            - ./node_modules

jobs:
  lint_typecheck:
    <<: *container_config
    steps:
      - prepare_linux
      - run: npm run lint
      - run: npm run typecheck

  build_linux:
    <<: *container_config
    steps:
      - prepare_linux
      - run: npm run build:linux
      - store_artifacts:
          path: dist
          destination: build

  build_win:
    executor:
      name: win/default
      size: 'medium'
    steps:
      - checkout
      - run:
          name: Change node version
          command: |
            nvm install 20.17.0
            nvm use 20.17.0
      - run:
          name: Install NuGet
          command: Invoke-WebRequest -Uri https://dist.nuget.org/win-x86-commandline/latest/nuget.exe -OutFile .\nuget.exe
      - run:
          name: Install BuildTools
          command: .\nuget.exe install Microsoft.Windows.SDK.BuildTools -Version 10.0.22621.3233 -x
      - run:
          name: Install Trusted Signing dlib
          command: .\nuget.exe install Microsoft.Trusted.Signing.Client -Version 1.0.53 -x
      - run:
          name: Set ENVs
          command: |
            $currentDir = (Get-Location).Path
            $signtoolPath = Join-Path -Path $currentDir -ChildPath "Microsoft.Windows.SDK.BuildTools\bin\10.0.22621.0\x64\signtool.exe"
            $codesigningDlibPath = Join-Path -Path $currentDir -ChildPath "Microsoft.Trusted.Signing.Client\bin\x64\Azure.CodeSigning.Dlib.dll"
            $metadataPath = Join-Path -Path $currentDir -ChildPath "metadata.json"
            setx SIGNTOOL_PATH $signtoolPath
            setx CODESIGNING_DLIB_PATH $codesigningDlibPath
            setx METADATA_PATH $metadataPath
      - run: pip install setuptools
      - run: npm ci --timeout 1500000
      - run: npm run build:win
      - store_artifacts:
          path: dist
          destination: build

workflows:
  version: 2
  verify_commit:
    jobs:
      # run test on every commit
      - lint_typecheck
  deploy:
    jobs:
      # build artifacts only on tags with name v.*
      - build_win:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v.*/
      - build_linux:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v.*/
