name: Build and Release macOS

on:
  push:
    branches:
      - '*'  

jobs:
  build_macos:
    runs-on: macos-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.14.2'
          
      - name: Install dependencies
        run: npm install node-pre-gyp --force
        
      - name: Install dependencies
        run: npm ci

      - name: Build macOS app
        run: npm run build:mac

      - name: Upload .dmg to GitHub Actions artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: dist/*.dmg