name: Build and Release macOS

on:
  push:
    tags:
      - 'v*'

jobs:
  build_macos:
    runs-on: macos-latest
    env:
      APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
      APPLE_ID: ${{ secrets.APPLE_ID }}
      APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
      APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
      CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
      CSC_LINK: ${{ secrets.CSC_LINK }}
      DEBUG: ${{ secrets.DEBUG }}
      VITE_SENTRY_DSN: ${{ secrets.VITE_SENTRY_DSN }}
      VITE_UNLIMIT_MERCHANT_ID: ${{ secrets.VITE_UNLIMIT_MERCHANT_ID }}
      VITE_UNLIMIT_BUY_TOKENS_IFRAME_URL: ${{ secrets.VITE_UNLIMIT_BUY_TOKENS_IFRAME_URL }}
      VITE_UNLIMIT_SELL_TOKENS_IFRAME_URL: ${{ secrets.VITE_UNLIMIT_SELL_TOKENS_IFRAME_URL }}
      VITE_CLICK_UP_KEY: ${{ secrets.VITE_CLICK_UP_KEY }}
      VITE_CLICK_UP_LIST_ID: ${{ secrets.VITE_CLICK_UP_LIST_ID }}
      VITE_CLICK_UP_ASSIGNEE_ID: ${{ secrets.VITE_CLICK_UP_ASSIGNEE_ID }}
      NODE_OPTIONS: ${{ secrets.NODE_OPTIONS }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      VITE_GA_MEASUREMENT_ID: ${{ secrets.VITE_GA_MEASUREMENT_ID }}
      VITE_GA_API_SECRET: ${{ secrets.VITE_GA_API_SECRET }}
      VITE_CRISP_WEBSITE_ID: ${{ secrets.VITE_CRISP_WEBSITE_ID }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.14.0'

      - name: Install dependencies
        run: brew install python-setuptools

      - name: Install dependencies
        run: npm ci

      - name: Build macOS app
        run: npm run build:mac
