name: Build and Release macOS

on:
  push:
    branches:
      - '*'  

jobs:
  build_macos:
    runs-on: macos-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.14.2'

      - name: Set node_options      
        run: export NODE_OPTIONS=--max_old_space_size=4096

      - name: Install dependencies
        run: brew install python@3.11

      - name: Install dependencies
        run: export PYTHON=3.11

      - name: Install dependencies
        run: export npm_config_python=/opt/homebrew/bin/python3.1


      - name: Install dependencies
        run: npm ci

      - name: Build macOS app
        run: npm run build:mac

      - name: Upload .dmg to GitHub Actions artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: dist/*.dmg
